### PR TITLE
Fix Debug assertion where value can be 255

### LINKED ISSUE #895: comparison in Debug.Assert of MIResults.cs
https://github.com/microsoft/MIEngine/blob/7637a9b6f6a081ed5b03e85b2ba252ddbb16c642/src/MICore/MIResults.cs#L983
`v <= 255`
i have catch this in str = `...value=\"-1 '\\377'\"...`

### PR DESCRIPTION
**Pull request by pieandcakes**
Fixes #895

### CODE REVIEW

File: src/MICore/MIResults.cs [hunk 1]
```diff
@@ -980,7 +980,7 @@ bool SpanOctalChars(string str, ref int i, StringBuilder output)
                         continue;
                     }
                 }
-                Debug.Assert(v < 255, "Value too large");
+                Debug.Assert(v <= 255, "Value too large");
```
Comment (WardenGnaw) [inline src/MICore/MIResults.cs]: nit: use Byte.MaxValue
